name: Build and Publish Docker Image to GitHub Packages

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Packages
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/pytorch_base:latest .
          docker tag ghcr.io/${{ github.repository }}/pytorch_base:latest ghcr.io/${{ github.repository }}/pytorch_base:${{ github.run_number }}

      - name: Push Docker image to GitHub Packages
        run: |
          docker push ghcr.io/${{ github.repository }}/pytorch_base:latest
          docker push ghcr.io/${{ github.repository }}/pytorch_base:${{ github.run_number }}
